### ISSUE TITLE
Callback not triggered with sdk ">=2.12.0 <3.0.0"

### ISSUE THREAD

**Issue by rulefahd** [rekab-app/background_locator#303]
did anyone find a fix??

**Comment by as2a3** [comment]
I found this problem when I did the last update(1.6.12), unfortunately I downgraded to version 1.6.6.
It And it didn't work again until after I also undo to my last commit.

This running problem occurred:

Execution failed for task ':background_locator:compileDebugKotlin'.
> Compilation error. See log for more details

I hope we can fix it soon.

**Comment by n0tc0ding** [comment]
Same issue after upgrading to 1.6.12

**Comment by CristianKoh1** [comment]
I have already submitted a merge request, solving this problem.

**Comment by mfirmansyahidris** [comment]
> I found this problem when I did the last update(1.6.12), unfortunately I downgraded to version 1.6.6. It And it didn't work again until after I also undo to my last commit.
> 
> This running problem occurred:
> 
> Execution failed for task ':background_locator:compileDebugKotlin'.
> 
> > Compilation error. See log for more details
> 
> I hope we can fix it soon.

try to remove pubspec.lock and run "pub clean"
